# coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paodekuai.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='paodekuai.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x0fpaodekuai.proto\"d\n\x08PlayData\x12\x11\n\thandcards\x18\x01 \x03(\x05\x12\x11\n\tplaycards\x18\x02 \x03(\x05\x12\x11\n\tlastcards\x18\x03 \x03(\x05\x12\x10\n\x08\x63\x61rdtype\x18\x04 \x01(\x05\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\".\n\nPlayResult\x12\x0e\n\x06result\x18\x01 \x03(\x05\x12\x10\n\x08\x63\x61rdtype\x18\x02 \x01(\x05\"\x1c\n\x0bShuffleData\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"=\n\rShuffleResult\x12\x10\n\x08\x63\x61rdlist\x18\x01 \x03(\x05\x12\r\n\x05\x66irst\x18\x02 \x01(\x05\x12\x0b\n\x03min\x18\x03 \x01(\x05\x32\\\n\tPaodekuai\x12$\n\x08playcard\x12\t.PlayData\x1a\x0b.PlayResult\"\x00\x12)\n\x07shuffle\x12\x0c.ShuffleData\x1a\x0e.ShuffleResult\"\x00\x42\x18\n\x14paodekuai.mode.protoP\x01\x62\x06proto3')
)

_PLAYDATA = _descriptor.Descriptor(
    name='PlayData',
    full_name='PlayData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='handcards', full_name='PlayData.handcards', index=0,
            number=1, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='playcards', full_name='PlayData.playcards', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lastcards', full_name='PlayData.lastcards', index=2,
            number=3, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cardtype', full_name='PlayData.cardtype', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='count', full_name='PlayData.count', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=19,
    serialized_end=119,
)

_PLAYRESULT = _descriptor.Descriptor(
    name='PlayResult',
    full_name='PlayResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='PlayResult.result', index=0,
            number=1, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='cardtype', full_name='PlayResult.cardtype', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=121,
    serialized_end=167,
)

_SHUFFLEDATA = _descriptor.Descriptor(
    name='ShuffleData',
    full_name='ShuffleData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='count', full_name='ShuffleData.count', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=169,
    serialized_end=197,
)

_SHUFFLERESULT = _descriptor.Descriptor(
    name='ShuffleResult',
    full_name='ShuffleResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='cardlist', full_name='ShuffleResult.cardlist', index=0,
            number=1, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='first', full_name='ShuffleResult.first', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='min', full_name='ShuffleResult.min', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=199,
    serialized_end=260,
)

DESCRIPTOR.message_types_by_name['PlayData'] = _PLAYDATA
DESCRIPTOR.message_types_by_name['PlayResult'] = _PLAYRESULT
DESCRIPTOR.message_types_by_name['ShuffleData'] = _SHUFFLEDATA
DESCRIPTOR.message_types_by_name['ShuffleResult'] = _SHUFFLERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayData = _reflection.GeneratedProtocolMessageType('PlayData', (_message.Message,), dict(
    DESCRIPTOR=_PLAYDATA,
    __module__='paodekuai_pb2'
    # @@protoc_insertion_point(class_scope:PlayData)
))
_sym_db.RegisterMessage(PlayData)

PlayResult = _reflection.GeneratedProtocolMessageType('PlayResult', (_message.Message,), dict(
    DESCRIPTOR=_PLAYRESULT,
    __module__='paodekuai_pb2'
    # @@protoc_insertion_point(class_scope:PlayResult)
))
_sym_db.RegisterMessage(PlayResult)

ShuffleData = _reflection.GeneratedProtocolMessageType('ShuffleData', (_message.Message,), dict(
    DESCRIPTOR=_SHUFFLEDATA,
    __module__='paodekuai_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleData)
))
_sym_db.RegisterMessage(ShuffleData)

ShuffleResult = _reflection.GeneratedProtocolMessageType('ShuffleResult', (_message.Message,), dict(
    DESCRIPTOR=_SHUFFLERESULT,
    __module__='paodekuai_pb2'
    # @@protoc_insertion_point(class_scope:ShuffleResult)
))
_sym_db.RegisterMessage(ShuffleResult)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024paodekuai.mode.protoP\001'))

_PAODEKUAI = _descriptor.ServiceDescriptor(
    name='Paodekuai',
    full_name='Paodekuai',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=262,
    serialized_end=354,
    methods=[
        _descriptor.MethodDescriptor(
            name='playcard',
            full_name='Paodekuai.playcard',
            index=0,
            containing_service=None,
            input_type=_PLAYDATA,
            output_type=_PLAYRESULT,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name='shuffle',
            full_name='Paodekuai.shuffle',
            index=1,
            containing_service=None,
            input_type=_SHUFFLEDATA,
            output_type=_SHUFFLERESULT,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_PAODEKUAI)

DESCRIPTOR.services_by_name['Paodekuai'] = _PAODEKUAI

# @@protoc_insertion_point(module_scope)
