# coding=utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mahjong_pb2 as mahjong__pb2


class MajongCalculateStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.calculate = channel.unary_unary(
            '/majong_rpc.MajongCalculate/calculate',
            request_serializer=mahjong__pb2.CalculateData.SerializeToString,
            response_deserializer=mahjong__pb2.CalculateResult.FromString,
        )
        self.settle = channel.unary_unary(
            '/majong_rpc.MajongCalculate/settle',
            request_serializer=mahjong__pb2.SettleData.SerializeToString,
            response_deserializer=mahjong__pb2.SettleResult.FromString,
        )
        self.shuffle = channel.unary_unary(
            '/majong_rpc.MajongCalculate/shuffle',
            request_serializer=mahjong__pb2.ShuffleData.SerializeToString,
            response_deserializer=mahjong__pb2.ShuffleResult.FromString,
        )
        self.baojiaoGang = channel.unary_unary(
            '/majong_rpc.MajongCalculate/baojiaoGang',
            request_serializer=mahjong__pb2.CalculateData.SerializeToString,
            response_deserializer=mahjong__pb2.Cards.FromString,
        )


class MajongCalculateServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def calculate(self, request, context):
        """进行麻将牌过程计算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def settle(self, request, context):
        """结算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shuffle(self, request, context):
        """洗牌函数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def baojiaoGang(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MajongCalculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'calculate': grpc.unary_unary_rpc_method_handler(
            servicer.calculate,
            request_deserializer=mahjong__pb2.CalculateData.FromString,
            response_serializer=mahjong__pb2.CalculateResult.SerializeToString,
        ),
        'settle': grpc.unary_unary_rpc_method_handler(
            servicer.settle,
            request_deserializer=mahjong__pb2.SettleData.FromString,
            response_serializer=mahjong__pb2.SettleResult.SerializeToString,
        ),
        'shuffle': grpc.unary_unary_rpc_method_handler(
            servicer.shuffle,
            request_deserializer=mahjong__pb2.ShuffleData.FromString,
            response_serializer=mahjong__pb2.ShuffleResult.SerializeToString,
        ),
        'baojiaoGang': grpc.unary_unary_rpc_method_handler(
            servicer.baojiaoGang,
            request_deserializer=mahjong__pb2.CalculateData.FromString,
            response_serializer=mahjong__pb2.Cards.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'majong_rpc.MajongCalculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
