# coding=utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import paodekuai_pb2 as paodekuai__pb2


class PaodekuaiStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.playcard = channel.unary_unary(
            '/Paodekuai/playcard',
            request_serializer=paodekuai__pb2.PlayData.SerializeToString,
            response_deserializer=paodekuai__pb2.PlayResult.FromString,
        )
        self.shuffle = channel.unary_unary(
            '/Paodekuai/shuffle',
            request_serializer=paodekuai__pb2.ShuffleData.SerializeToString,
            response_deserializer=paodekuai__pb2.ShuffleResult.FromString,
        )
        self.yitiaolong = channel.unary_unary(
            '/Paodekuai/yitiaolong',
            request_serializer=paodekuai__pb2.UserCards.SerializeToString,
            response_deserializer=paodekuai__pb2.YitiaolongResult.FromString,
        )


class PaodekuaiServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def playcard(self, request, context):
        """出牌
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shuffle(self, request, context):
        """洗牌函数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def yitiaolong(self, request, context):
        """洗牌函数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaodekuaiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'playcard': grpc.unary_unary_rpc_method_handler(
            servicer.playcard,
            request_deserializer=paodekuai__pb2.PlayData.FromString,
            response_serializer=paodekuai__pb2.PlayResult.SerializeToString,
        ),
        'shuffle': grpc.unary_unary_rpc_method_handler(
            servicer.shuffle,
            request_deserializer=paodekuai__pb2.ShuffleData.FromString,
            response_serializer=paodekuai__pb2.ShuffleResult.SerializeToString,
        ),
        'yitiaolong': grpc.unary_unary_rpc_method_handler(
            servicer.yitiaolong,
            request_deserializer=paodekuai__pb2.UserCards.FromString,
            response_serializer=paodekuai__pb2.YitiaolongResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Paodekuai', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
